## USB port
port: /dev/ttyUSB0


##### Calibration ####
### accelerometer
accel_x_min: -265.0
accel_x_max: 253.0
accel_y_min: -254.0
accel_y_max: 263.0
accel_z_min: -275.0
accel_z_max: 240.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
# Calibration values with the two GPS units mounted
calibration_magn_use_extended: true
magn_ellipsoid_center: [235.763, 26.5002, 204.774]
magn_ellipsoid_transform: [[0.906274, 0.0256863, 0.0141310], [0.0256863, 0.851375, 0.0216864], [0.0141310, 0.0216864, 0.993256]]
# Calibration values with just the camera mounted
#calibration_magn_use_extended: true
#magn_ellipsoid_center: [147.915, -55.2544, 138.007]
#magn_ellipsoid_transform: [[0.799802, -0.0289665, -0.0336112], [-0.0289665, 0.854718, 0.00703856], [-0.0336112, 0.00703856, 0.993353]]
# Default calibration values
#calibration_magn_use_extended: false
#magn_ellipsoid_center: [0, 0, 0]
#magn_ellipsoid_transform: [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -20.12
gyro_average_offset_y: 59.14
gyro_average_offset_z: 1.88
