# Settings for the razor 9dof stick 

## USB port
port: /dev/ttyACM5


##### Calibration ####
### accelerometer
accel_x_min: -275.0
accel_x_max: 244.0
accel_y_min: -262.0
accel_y_max: 274.0
accel_z_min: -247.0
accel_z_max: 264.0

### magnetometer
# standard calibration
magn_x_min: -600.0
magn_x_max: 600.0
magn_y_min: -600.0
magn_y_max: 600.0
magn_z_min: -600.0
magn_z_max: 600.0

# extended calibration
calibration_magn_use_extended: false
magn_ellipsoid_center: [0, 0, 0]
magn_ellipsoid_transform: [[0, 0, 0], [0, 0, 0], [0, 0, 0]]

# AHRS to robot calibration
imu_yaw_calibration: 0.0

### gyroscope
gyro_average_offset_x: -17.49
gyro_average_offset_y: 0.81
gyro_average_offset_z: -6.63
